
services:
  #PostgreSQL
  db:
    image: postgres:15
    container_name: artreview_db
    restart: always
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: artreview
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

  #Backend FastAPI
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: artreview_backend
    restart: always
    environment:
      DATABASE_URL: postgresql://postgres:postgres@db:5432/artreview
      SECRET_KEY: change_me_to_a_strong_one
      AZURE_STORAGE_CONNECTION_STRING: ""
      AZURE_CONTAINER_NAME: artworks
      MAX_DAILY_UPLOADS: 5
      MAX_DAILY_REVIEWS: 5
      BACKEND_URL: http://backend:8000
    ports:
      - "8000:8000"
    depends_on:
      db:
        condition: service_healthy
  
    volumes:
      - ./shared_uploads:/shared_uploads
    command: >
      sh -c "uvicorn app.main:app --host 0.0.0.0 --port 8000 --reload"

  adminer:
      image: adminer
      restart: always
      ports:
        - "8080:8080"
      depends_on:
        - db

    
  app:
    build: 
      context: ./backend
      dockerfile: Dockerfile
    container_name: my_app
    volumes:
      - uploads_volume:/usr/share/nginx/html/uploads
    environment:
      - LOCAL_UPLOAD_DIR=/usr/share/nginx/html/uploads

  nginx:
    image: nginx:alpine
    ports:
      - "3000:80"
    volumes:
      - ./shared_uploads:/shared_uploads
      - ./nginx:/etc/nginx/conf.d
      - "C:/Users/Gdriv/Desktop/projekt programowanie/Inzynieria-oprogramowania-proj/frontend/dist:/usr/share/nginx/html"
    depends_on:
      - backend

volumes:
  uploads_volume:
  pgdata: